//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace magistr
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentOfWell
    {
        public int id { get; set; }
        public int idStudent { get; set; }
        public int idWell { get; set; }
    
        public virtual Student Student { get; set; }
        public virtual Well Well { get; set; }
    }
}
