//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace magistr
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentActivity
    {
        public int idActivity { get; set; }
        public int idStudent { get; set; }
        public string attendance { get; set; }
        public string reasonforAbsence { get; set; }
        public Nullable<decimal> PercentageOfEarnedMaterial { get; set; }
    
        public virtual Activity Activity { get; set; }
        public virtual Student Student { get; set; }
    }
}
